In [2]:
from numpy import *

In [3]:
#随机数 4*4的矩阵
random.rand(4, 4)

array([[0.07188171, 0.13147015, 0.47376387, 0.75057909],
       [0.66937336, 0.20881996, 0.88585402, 0.66692066],
       [0.6797852 , 0.13832765, 0.87277335, 0.33945553],
       [0.30453644, 0.48514467, 0.36106667, 0.96275041]])

In [4]:
#调用mat()函数可以将数组化为矩阵
randMat = mat(random.rand(4, 4))

In [5]:
#.I操作符实现了矩阵求逆的运算
randMat.I

matrix([[-21.74966682,  11.61146157,  11.02273741, -21.7051839 ],
        [-32.52363462,  13.31344192,  30.09626406, -43.96188114],
        [ 35.62070922, -16.45366136, -21.09468949,  36.43254951],
        [ 12.40932769,  -5.35441515, -11.21379892,  18.83011447]])

In [6]:
#将逆矩阵储存起来
invRandMat = randMat.I

In [7]:
#得到的应该是单位矩阵，在计算机里显示的很小的值可以看做是0
randMat * invRandMat

matrix([[ 1.00000000e+00, -1.11022302e-15, -4.44089210e-16,
          3.55271368e-15],
        [-8.88178420e-16,  1.00000000e+00,  1.77635684e-15,
          3.55271368e-15],
        [-4.44089210e-16, -2.22044605e-16,  1.00000000e+00,
         -8.88178420e-16],
        [ 8.60422844e-16, -3.33066907e-16, -8.32667268e-17,
          1.00000000e+00]])

In [8]:
myEye = randMat * invRandMat

In [9]:
#可以看到最后的结果是0矩阵
myEye - eye(4)

matrix([[ 1.77635684e-15, -1.11022302e-15, -4.44089210e-16,
          3.55271368e-15],
        [-8.88178420e-16,  6.66133815e-16,  1.77635684e-15,
          3.55271368e-15],
        [-4.44089210e-16, -2.22044605e-16,  8.88178420e-16,
         -8.88178420e-16],
        [ 8.60422844e-16, -3.33066907e-16, -8.32667268e-17,
          2.22044605e-16]])