In [3]:
from numpy import *

In [4]:
#随机数 4*4的矩阵
random.rand(4, 4)

array([[0.17405364, 0.3517937 , 0.84914308, 0.23353483],
       [0.52919678, 0.48062091, 0.42232995, 0.22071502],
       [0.45647952, 0.46560275, 0.77344745, 0.84942335],
       [0.82715159, 0.37380676, 0.1960117 , 0.37556069]])

In [5]:
#调用mat()函数可以将数组化为矩阵
randMat = mat(random.rand(4, 4))

In [6]:
#.I操作符实现了矩阵求逆的运算
randMat.I

matrix([[  1.07947392,   0.30403237,  -0.36111784,  -0.36383454],
        [  8.62723101,  -7.34776795,  11.57173463,  -7.02384321],
        [-18.57619125,  18.01406038, -22.17798942,  10.69569932],
        [ 12.9944545 , -13.53374677,  16.25891982,  -6.11472081]])

In [7]:
#将逆矩阵储存起来
invRandMat = randMat.I

In [7]:
#得到的应该是单位矩阵，在计算机里显示的很小的值可以看做是0
randMat * invRandMat

matrix([[ 1.00000000e+00, -1.11022302e-15, -4.44089210e-16,
          3.55271368e-15],
        [-8.88178420e-16,  1.00000000e+00,  1.77635684e-15,
          3.55271368e-15],
        [-4.44089210e-16, -2.22044605e-16,  1.00000000e+00,
         -8.88178420e-16],
        [ 8.60422844e-16, -3.33066907e-16, -8.32667268e-17,
          1.00000000e+00]])

In [8]:
myEye = randMat * invRandMat

In [9]:
#可以看到最后的结果是0矩阵
myEye - eye(4)

matrix([[ 1.77635684e-15, -1.11022302e-15, -4.44089210e-16,
          3.55271368e-15],
        [-8.88178420e-16,  6.66133815e-16,  1.77635684e-15,
          3.55271368e-15],
        [-4.44089210e-16, -2.22044605e-16,  8.88178420e-16,
         -8.88178420e-16],
        [ 8.60422844e-16, -3.33066907e-16, -8.32667268e-17,
          2.22044605e-16]])